version: '3'

output: prefixed

tasks:

  build:
    deps: [build-container-a, build-container-b]

  up:
    cmds: 
      - docker-compose up -d

  status:
    cmds:
      - docker-compose ps

  down:
    cmds:
      - docker-compose down 

  build-container-a:
    cmds:
      - docker build -t app_a:0 Docker/app_a

  build-container-b:
    cmds:
      - docker build -t app_b:0 Docker/app_b
